site_name: Fueny
theme:
  name: material
  palette:
    # 樱花主题配色
    primary: pink
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.copy
  font:
    text: Noto Sans SC
    code: Roboto Mono
  icon:
    logo: material/flower
    repo: fontawesome/brands/github

# 自定义CSS
extra_css:
  - stylesheets/extra.css


# 网站信息
site_description: Fueny博客站点
site_author: Fueny

# 导航结构
nav:
  - 首页: index.md
  - 关于: about.md
  - 博客:
    - posts/ai_history.md
    - posts/machine_learning.md
    - posts/deep_learning.md
    - posts/nlp.md
    - posts/ai_ethics.md
