site_name: Fueny
theme:
  name: material
  palette:
    # 主题配色
    primary: pink
    accent: deep purple
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.suggest
    - content.tabs.link
    - content.code.copy
  font:
    text: Noto Sans SC
    code: Roboto Mono
  icon:
    logo: material/flower
    repo: fontawesome/brands/github

# 自定义CSS
extra_css:
  - stylesheets/extra.css


# 网站信息
site_description: Fueny的个人博客站点
site_author: Fueny

# 导航结构
nav:
  - 首页: index.md
  - 关于: about.md
  - 博客目录: catalogs.md
  - 生活博客:
    - 技术分享: posts/blog1.md
    - 生活感悟: posts/blog2.md
    - 读书笔记: posts/blog3.md
    - 旅行记录: posts/blog4.md
    - 项目分享: posts/blog5.md
  - AI博客:
    - AI发展简史: posts/ai_history.md
    - 机器学习基础: posts/machine_learning.md
    - 深度学习入门: posts/deep_learning.md
    - 自然语言处理技术: posts/nlp.md
    - AI伦理与未来: posts/ai_ethics.md
