name: 部署 MkDocs 网站

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

# 设置权限
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取完整的历史记录

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          # 如果您有其他依赖，请在这里添加

      - name: 构建文档
        run: mkdocs build

      - name: 部署到 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site  # MkDocs 生成的站点文件夹
          branch: gh-pages  # 部署到的分支
          clean: true  # 清除旧文件
